### ISSUE TITLE
Missing property `chargeBearer` in periodic payments

### ISSUE THREAD

**Issue by yves-bussard** [openbankingproject-ch/obp-apis#41]
In the table which describes all properties for each payment type there is a property `chargeBearer` which is missing in the model periodicPaymentInitiation_json but exists in the model paymentInitiation_json.

Either we remove that property from the description or we add it to the model.

**Comment by wishopt** [comment]
In the [NextGenPSD2 XS2A Framework yaml](https://github.com/openbankingproject-ch/obp-apis/blob/master/swiss-ng-api/berlin-group-documentation/psd2-api%201.3.8%2020201118v1.yaml), the tables describing the models are different, as periodicPaymentInitiation_json and paymentInitiation_json have different properties. The tables in the [swiss-ng-api.yaml](https://github.com/openbankingproject-ch/obp-apis/blob/master/swiss-ng-api.yaml) have been copy-pasted and are identical, which is why the model isn't described correctly.

As the tables in the swiss-ng-api.yaml seem to be out of date anyway (see #44), we will thoroughly check the table and model of  paymentInitiation_json in a first step. After that, we will update the tables of periodicPaymentInitiation_json and paymentInitiationBulkElement_json to correctly represent the models.

This will also fix the issues #35, #36, #37, #38, #39, #40 and #42
